[package]
name = "basic-clipper"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug.workspace = true
valib = { workspace = true, features = ["saturators", "filters", "oversample", "nih-plug"] }
